version: "3.3"

networks:
  web:
    external: true
  internal:
    external: false

services:
  # db:
  #   image: "mcr.microsoft.com/mssql/server"
  #   environment:
  #       SA_PASSWORD: "Your_password123"
  #       ACCEPT_EULA: "Y"
  #   ports:
  #     - "1433:1433"    
  redis:
    image: redis:latest
    restart: always
    # ports:
    #   - "6379:6379"
    networks:
      - internal
    # user: 
    #   - root  
    # volumes: 
    #   - ./data:/data  
  email-service:
    build:
      context: ./email-service
    restart: always
    environment:
      - PORT=5000
    ports:
      - "5000:5000"
    labels:
      - traefik.http.routers.email.rule=Host(`email.api.cvac.net.au`)
      - traefik.http.routers.email.tls=true
      - traefik.http.routers.email.tls.certresolver=lets-encrypt
      - traefik.port=5000
    networks:
      - internal
      - web

  api:
    image: cva-api
    build:
      context: .
    restart: always
    depends_on:
      - redis
      - email-service
      # - db
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    ports:
      - "5001:80"

    # environment:
    #   - REDIS_URL=redis:6379
    #   - ASPNETCORE_ENVIRONMENT=Development
    #   - ASPNETCORE_URLS=https://+:5000;http://+:80
    #   - ASPNETCORE_HTTPS_PORT=5000
    #   - ASPNETCORE_Kestrel__Certificates__Default__Password=cva
    #   - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/cva.pfx
    links:
      - redis:redis
      - email-service:email-service
      # - db:db
    labels:
      - traefik.http.routers.cvaapi.rule=Host(`v2.api.cvac.net.au`)
      - traefik.http.routers.cvaapi.tls=true
      - traefik.http.routers.cvaapi.tls.certresolver=lets-encrypt
      - traefik.port=5001
    networks:
      - internal
      - web
    # volumes:
    #   - ./https/aspnetapp.pfx:/https/aspnetapp.pfx:ro